### ISSUE TITLE
Can't set scale to Metric?

### ISSUE THREAD

**Issue by danieldooley** [daniellsu/leaflet-betterscale#1]
Hi, it seems for whatever reason Metric does not work. I had a quick dive into the code and it seems that mScale is not defined? Doesn't look like it's created anywhere.

This is the code I'm trying:

```
mc.scaleBar = L.control.betterscale({metric: true, imperial: false});
mc.scaleBar.addTo(mc.map);
```

And it's throwing this error:
```
TypeError: Cannot read property 'style' of undefined
    at NewClass._updateMetric (L.Control.BetterScale.js:50)
    at NewClass._updateScales (L.Control.BetterScale.js:46)
    at NewClass._update (L.Control.BetterScale.js:43)
```

Am I doing something wrong or is it just that Metric isn't supported?

**Comment by Stezii** [comment]
Use this function: 

```
_updateMetric: function (t) {
	var e = this._getRoundNum(t), i, n, o, s, a,
            r = this._iScaleFirstNumber,
            h = this._iScaleSecondNumber,
            l = this._iScale,
            u = this._iScaleLabel;
			
        u.innerHTML = "0", 1e3 > e ? (i = this._getRoundNum(e), o = this._getRoundNum(e / 2), l.style.width = this._getScaleWidth(e / t) + "px", r.innerHTML = o, h.innerHTML = i + "m") : (a=e/1e3, n = this._getRoundNum(a), s = this._getRoundNum(a / 2), l.style.width = this._getScaleWidth(n / a) + "px", r.innerHTML = s, h.innerHTML = n + "km")
    }
```

**Comment by onlyMaps** [comment]
I am sorry, but i can’t still figure out how to turn on the metric values for the scalebar. I would be very great full for your help to get this running. Is it possible for you to make a new release or to get more specific how and where to make changes to get it running?

**Comment by Stezii** [comment]
Just overwrite the sourcecode [here](https://github.com/daniellsu/leaflet-betterscale/blob/master/L.Control.BetterScale.js#L37) with [my modification](https://github.com/daniellsu/leaflet-betterscale/issues/1#issuecomment-270718941). 
However use it with caution, I haven't had the time to validate it!

**Comment by daniellsu** [comment]
Hi,
Here in the United States we seem to forget the rest of the world uses a scientific method for measurement instead of how big some dead guys foot was, lol.  I have posted a fix, it looks right, and to follow a saying, "trust, but verify".
Here's a JSBIN demonstrating the fix:https://jsbin.com/huwaxilafa/edit?html,output


On ‎Thursday‎, ‎May‎ ‎4‎, ‎2017‎ ‎10‎:‎24‎:‎41‎ ‎AM‎ ‎EDT, Søren Birch-Petersen <notifications@github.com> wrote:
I am sorry, but i can’t still figure out how to turn on the metric values for the scalebar. I would be very great full for your help to get this running. Is it possible for you to make a new release or to get more specific how and where to make changes to get it running?

**Comment by onlyMaps** [comment]
Thanks – appreciate your fast replay – owe you one of the attached :-)

![carlsberg](https://cloud.githubusercontent.com/assets/6785759/25720358/ece13a80-310c-11e7-8f6c-cd1c0d06b1c1.jpg)
